[[0;32m+[0m][0;32m /log/firmware/firmware/usr/lib/python3.8/lib2to3/fixer_util.py[0m
294:def find_root(node):.
300:se ValueError("root found before f.
308:ing(name, find_root(node), package.
322:    root = find_root(no.
324:package, name, root):.
330:e in enumerate(root.children):.
333:2 in enumerate(root.children[idx:].
342:e in enumerate(root.children):.
357:    root.insert_child(i.
