<!-- 
emba - EMBEDDED LINUX ANALYZER

Copyright 2020-2021 Siemens AG
Copyright 2020-2021 Siemens Energy AG

emba comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
welcome to redistribute it under the terms of the GNU General Public License.
See LICENSE file for usage of this software.

emba is licensed under GPLv3

Author(s): Michael Messner, Pascal Eckmann, Stefan Haboeck
-->

<!-- Used icons: https://github.com/CoreyGinnivan/system-uicons -->
 
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EMBA firmware report</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="./../style/style.css" type="text/css">
  <link rel="icon" type="image/png" href="./../style/favicon.png">
</head>
<body>

<div id="sidenav" class="side">
  <div class="logo">
    <a class="inherit" href="./../index.html"><img class="inherit" src="./../style/emba.svg" alt="emba logo"></a>
  </div>
  <div id="nav">
      <a class="back" href="./../index.html">&laquo; Back to main</a>
<a class="modul" href="./../s21_python_check.html" title="./../s21_python_check.html" >&laquo; Back to s21_python_check</a>
      <!-- navigation start -->
      <!-- navigation end -->
      <input id="expand" class="expand_njs hidden" type="button" value="More results:" onclick="this.value=this.value=='+ Show more results'?'- Hide more results':'+ Show more results';">
      <div class="expand_area">
        <!-- etc start -->
        <!-- etc end -->
      </div>
  </div>
  <a href="TIMELINK"><div id="buttonTimeInvisible" class="rectButton"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="white" stroke-linecap="round" stroke-linejoin="round" transform="matrix(-1 0 0 1 19 2)"><circle cx="8.5" cy="8.5" r="8"/><path d="M8.5 5.5v4H5"/></g></svg></div></a>
  <div id="buttonSizer" class="rectButton buttonClose" onclick="buttonNav()"></div>
</div>
<div id="main" class="main">
  <!-- content start -->
<pre>************* Module gpg.gpgme</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:52:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:54:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:61:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:75:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1:0: C0302: Too many lines in module (3692/1000) (too-many-lines)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:3692:0: C0305: Trailing newlines (trailing-newlines)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:10:8: C0415: Import outside toplevel (importlib) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:21:8: C0415: Import outside toplevel (os.path.dirname) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:22:8: C0415: Import outside toplevel (imp) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:23:8: C0103: Variable name "fp" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:25:12: C0103: Variable name "fp" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:27:12: C0415: Import outside toplevel (_gpgme) (import-outside-toplevel)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:42:4: C0103: Class name "_swig_property" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:51:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:86:11: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:93:7: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:92:4: C0103: Constant name "_newclass" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:94:4: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:96:4: C0103: Constant name "_newclass" doesn't conform to UPPER_CASE naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:106:0: C0103: Class name "_gpgme_sig_notation" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:106:0: R0205: Class '_gpgme_sig_notation' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:114:34: W0212: Access to a protected member _gpgme_sig_notation_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:115:34: W0212: Access to a protected member _gpgme_sig_notation_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:118:35: W0212: Access to a protected member _gpgme_sig_notation_value_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:119:35: W0212: Access to a protected member _gpgme_sig_notation_value_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:122:35: W0212: Access to a protected member _gpgme_sig_notation_flags_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:123:35: W0212: Access to a protected member _gpgme_sig_notation_flags_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:126:44: W0212: Access to a protected member _gpgme_sig_notation_human_readable_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:127:44: W0212: Access to a protected member _gpgme_sig_notation_human_readable_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:130:38: W0212: Access to a protected member _gpgme_sig_notation_critical_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:131:38: W0212: Access to a protected member _gpgme_sig_notation_critical_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:140:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:139:12: E0203: Access to member 'this' before its definition line 141 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:106:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:144:35: W0212: Access to a protected member _gpgme_sig_notation_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:195:14: W0212: Access to a protected member _ALL_SOURCE of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:196:14: W0212: Access to a protected member _GNU_SOURCE of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:197:27: W0212: Access to a protected member _POSIX_PTHREAD_SEMANTICS of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:198:17: W0212: Access to a protected member _TANDEM_SOURCE of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:201:27: W0212: Access to a protected member _DARWIN_USE_64_BIT_INODE of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:202:13: W0212: Access to a protected member _REENTRANT of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:207:31: W0212: Access to a protected member _GPGME_OBSOLETE_SOME_SYMBOLS of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:367:0: C0103: Class name "_gpgme_engine_info" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:367:0: R0205: Class '_gpgme_engine_info' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:375:38: W0212: Access to a protected member _gpgme_engine_info_protocol_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:376:38: W0212: Access to a protected member _gpgme_engine_info_protocol_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:379:39: W0212: Access to a protected member _gpgme_engine_info_file_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:380:39: W0212: Access to a protected member _gpgme_engine_info_file_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:383:37: W0212: Access to a protected member _gpgme_engine_info_version_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:384:37: W0212: Access to a protected member _gpgme_engine_info_version_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:387:41: W0212: Access to a protected member _gpgme_engine_info_req_version_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:388:41: W0212: Access to a protected member _gpgme_engine_info_req_version_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:391:38: W0212: Access to a protected member _gpgme_engine_info_home_dir_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:392:38: W0212: Access to a protected member _gpgme_engine_info_home_dir_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:401:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:400:12: E0203: Access to member 'this' before its definition line 402 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:367:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:405:34: W0212: Access to a protected member _gpgme_engine_info_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:408:0: C0103: Class name "_gpgme_tofu_info" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:408:0: R0205: Class '_gpgme_tofu_info' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:416:38: W0212: Access to a protected member _gpgme_tofu_info_validity_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:417:38: W0212: Access to a protected member _gpgme_tofu_info_validity_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:420:36: W0212: Access to a protected member _gpgme_tofu_info_policy_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:421:36: W0212: Access to a protected member _gpgme_tofu_info_policy_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:424:34: W0212: Access to a protected member _gpgme_tofu_info__rfu_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:425:34: W0212: Access to a protected member _gpgme_tofu_info__rfu_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:428:39: W0212: Access to a protected member _gpgme_tofu_info_signcount_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:429:39: W0212: Access to a protected member _gpgme_tofu_info_signcount_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:432:39: W0212: Access to a protected member _gpgme_tofu_info_encrcount_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:433:39: W0212: Access to a protected member _gpgme_tofu_info_encrcount_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:436:39: W0212: Access to a protected member _gpgme_tofu_info_signfirst_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:437:39: W0212: Access to a protected member _gpgme_tofu_info_signfirst_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:440:38: W0212: Access to a protected member _gpgme_tofu_info_signlast_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:441:38: W0212: Access to a protected member _gpgme_tofu_info_signlast_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:444:39: W0212: Access to a protected member _gpgme_tofu_info_encrfirst_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:445:39: W0212: Access to a protected member _gpgme_tofu_info_encrfirst_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:448:38: W0212: Access to a protected member _gpgme_tofu_info_encrlast_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:449:38: W0212: Access to a protected member _gpgme_tofu_info_encrlast_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:452:41: W0212: Access to a protected member _gpgme_tofu_info_description_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:453:41: W0212: Access to a protected member _gpgme_tofu_info_description_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:457:4: E0102: method already defined line 415 (function-redefined)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:471:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:470:12: E0203: Access to member 'this' before its definition line 472 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:408:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:475:32: W0212: Access to a protected member _gpgme_tofu_info_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:478:0: C0103: Class name "_gpgme_subkey" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:478:0: R0205: Class '_gpgme_subkey' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:486:37: W0212: Access to a protected member _gpgme_subkey_revoked_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:487:37: W0212: Access to a protected member _gpgme_subkey_revoked_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:490:37: W0212: Access to a protected member _gpgme_subkey_expired_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:491:37: W0212: Access to a protected member _gpgme_subkey_expired_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:494:38: W0212: Access to a protected member _gpgme_subkey_disabled_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:495:38: W0212: Access to a protected member _gpgme_subkey_disabled_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:498:37: W0212: Access to a protected member _gpgme_subkey_invalid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:499:37: W0212: Access to a protected member _gpgme_subkey_invalid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:502:41: W0212: Access to a protected member _gpgme_subkey_can_encrypt_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:503:41: W0212: Access to a protected member _gpgme_subkey_can_encrypt_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:506:38: W0212: Access to a protected member _gpgme_subkey_can_sign_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:507:38: W0212: Access to a protected member _gpgme_subkey_can_sign_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:510:41: W0212: Access to a protected member _gpgme_subkey_can_certify_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:511:41: W0212: Access to a protected member _gpgme_subkey_can_certify_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:514:36: W0212: Access to a protected member _gpgme_subkey_secret_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:515:36: W0212: Access to a protected member _gpgme_subkey_secret_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:518:46: W0212: Access to a protected member _gpgme_subkey_can_authenticate_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:519:46: W0212: Access to a protected member _gpgme_subkey_can_authenticate_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:522:42: W0212: Access to a protected member _gpgme_subkey_is_qualified_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:523:42: W0212: Access to a protected member _gpgme_subkey_is_qualified_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:526:40: W0212: Access to a protected member _gpgme_subkey_is_cardkey_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:527:40: W0212: Access to a protected member _gpgme_subkey_is_cardkey_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:530:38: W0212: Access to a protected member _gpgme_subkey_is_de_vs_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:531:38: W0212: Access to a protected member _gpgme_subkey_is_de_vs_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:534:37: W0212: Access to a protected member _gpgme_subkey__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:535:37: W0212: Access to a protected member _gpgme_subkey__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:538:41: W0212: Access to a protected member _gpgme_subkey_pubkey_algo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:539:41: W0212: Access to a protected member _gpgme_subkey_pubkey_algo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:542:36: W0212: Access to a protected member _gpgme_subkey_length_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:543:36: W0212: Access to a protected member _gpgme_subkey_length_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:546:35: W0212: Access to a protected member _gpgme_subkey_keyid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:547:35: W0212: Access to a protected member _gpgme_subkey_keyid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:550:36: W0212: Access to a protected member _gpgme_subkey__keyid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:551:36: W0212: Access to a protected member _gpgme_subkey__keyid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:554:33: W0212: Access to a protected member _gpgme_subkey_fpr_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:555:33: W0212: Access to a protected member _gpgme_subkey_fpr_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:558:39: W0212: Access to a protected member _gpgme_subkey_timestamp_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:559:39: W0212: Access to a protected member _gpgme_subkey_timestamp_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:562:37: W0212: Access to a protected member _gpgme_subkey_expires_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:563:37: W0212: Access to a protected member _gpgme_subkey_expires_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:566:41: W0212: Access to a protected member _gpgme_subkey_card_number_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:567:41: W0212: Access to a protected member _gpgme_subkey_card_number_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:570:35: W0212: Access to a protected member _gpgme_subkey_curve_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:571:35: W0212: Access to a protected member _gpgme_subkey_curve_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:574:37: W0212: Access to a protected member _gpgme_subkey_keygrip_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:575:37: W0212: Access to a protected member _gpgme_subkey_keygrip_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:579:4: E0102: method already defined line 485 (function-redefined)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:593:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:592:12: E0203: Access to member 'this' before its definition line 594 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:478:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:597:29: W0212: Access to a protected member _gpgme_subkey_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:600:0: C0103: Class name "_gpgme_key_sig" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:600:0: R0205: Class '_gpgme_key_sig' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:608:37: W0212: Access to a protected member _gpgme_key_sig_revoked_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:609:37: W0212: Access to a protected member _gpgme_key_sig_revoked_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:612:37: W0212: Access to a protected member _gpgme_key_sig_expired_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:613:37: W0212: Access to a protected member _gpgme_key_sig_expired_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:616:37: W0212: Access to a protected member _gpgme_key_sig_invalid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:617:37: W0212: Access to a protected member _gpgme_key_sig_invalid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:620:40: W0212: Access to a protected member _gpgme_key_sig_exportable_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:621:40: W0212: Access to a protected member _gpgme_key_sig_exportable_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:624:37: W0212: Access to a protected member _gpgme_key_sig__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:625:37: W0212: Access to a protected member _gpgme_key_sig__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:628:41: W0212: Access to a protected member _gpgme_key_sig_pubkey_algo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:629:41: W0212: Access to a protected member _gpgme_key_sig_pubkey_algo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:632:35: W0212: Access to a protected member _gpgme_key_sig_keyid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:633:35: W0212: Access to a protected member _gpgme_key_sig_keyid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:636:36: W0212: Access to a protected member _gpgme_key_sig__keyid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:637:36: W0212: Access to a protected member _gpgme_key_sig__keyid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:640:39: W0212: Access to a protected member _gpgme_key_sig_timestamp_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:641:39: W0212: Access to a protected member _gpgme_key_sig_timestamp_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:644:37: W0212: Access to a protected member _gpgme_key_sig_expires_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:645:37: W0212: Access to a protected member _gpgme_key_sig_expires_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:648:36: W0212: Access to a protected member _gpgme_key_sig_status_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:649:36: W0212: Access to a protected member _gpgme_key_sig_status_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:652:45: W0212: Access to a protected member _gpgme_key_sig__obsolete_class_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:653:45: W0212: Access to a protected member _gpgme_key_sig__obsolete_class_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:656:33: W0212: Access to a protected member _gpgme_key_sig_uid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:657:33: W0212: Access to a protected member _gpgme_key_sig_uid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:660:34: W0212: Access to a protected member _gpgme_key_sig_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:661:34: W0212: Access to a protected member _gpgme_key_sig_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:664:35: W0212: Access to a protected member _gpgme_key_sig_email_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:665:35: W0212: Access to a protected member _gpgme_key_sig_email_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:668:37: W0212: Access to a protected member _gpgme_key_sig_comment_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:669:37: W0212: Access to a protected member _gpgme_key_sig_comment_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:672:39: W0212: Access to a protected member _gpgme_key_sig_sig_class_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:673:39: W0212: Access to a protected member _gpgme_key_sig_sig_class_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:676:39: W0212: Access to a protected member _gpgme_key_sig_notations_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:677:39: W0212: Access to a protected member _gpgme_key_sig_notations_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:680:44: W0212: Access to a protected member _gpgme_key_sig__last_notation_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:681:44: W0212: Access to a protected member _gpgme_key_sig__last_notation_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:685:4: E0102: method already defined line 607 (function-redefined)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:699:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:698:12: E0203: Access to member 'this' before its definition line 700 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:600:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:703:30: W0212: Access to a protected member _gpgme_key_sig_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:706:0: C0103: Class name "_gpgme_user_id" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:706:0: R0205: Class '_gpgme_user_id' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:714:37: W0212: Access to a protected member _gpgme_user_id_revoked_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:715:37: W0212: Access to a protected member _gpgme_user_id_revoked_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:718:37: W0212: Access to a protected member _gpgme_user_id_invalid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:719:37: W0212: Access to a protected member _gpgme_user_id_invalid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:722:37: W0212: Access to a protected member _gpgme_user_id__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:723:37: W0212: Access to a protected member _gpgme_user_id__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:726:36: W0212: Access to a protected member _gpgme_user_id_origin_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:727:36: W0212: Access to a protected member _gpgme_user_id_origin_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:730:38: W0212: Access to a protected member _gpgme_user_id_validity_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:731:38: W0212: Access to a protected member _gpgme_user_id_validity_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:734:33: W0212: Access to a protected member _gpgme_user_id_uid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:735:33: W0212: Access to a protected member _gpgme_user_id_uid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:738:34: W0212: Access to a protected member _gpgme_user_id_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:739:34: W0212: Access to a protected member _gpgme_user_id_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:742:35: W0212: Access to a protected member _gpgme_user_id_email_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:743:35: W0212: Access to a protected member _gpgme_user_id_email_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:746:37: W0212: Access to a protected member _gpgme_user_id_comment_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:747:37: W0212: Access to a protected member _gpgme_user_id_comment_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:750:40: W0212: Access to a protected member _gpgme_user_id_signatures_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:751:40: W0212: Access to a protected member _gpgme_user_id_signatures_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:754:42: W0212: Access to a protected member _gpgme_user_id__last_keysig_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:755:42: W0212: Access to a protected member _gpgme_user_id__last_keysig_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:758:37: W0212: Access to a protected member _gpgme_user_id_address_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:759:37: W0212: Access to a protected member _gpgme_user_id_address_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:762:34: W0212: Access to a protected member _gpgme_user_id_tofu_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:763:34: W0212: Access to a protected member _gpgme_user_id_tofu_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:766:41: W0212: Access to a protected member _gpgme_user_id_last_update_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:767:41: W0212: Access to a protected member _gpgme_user_id_last_update_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:771:4: E0102: method already defined line 713 (function-redefined)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:785:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:784:12: E0203: Access to member 'this' before its definition line 786 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:706:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:789:30: W0212: Access to a protected member _gpgme_user_id_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:792:0: C0103: Class name "_gpgme_key" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:792:0: R0205: Class '_gpgme_key' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:800:35: W0212: Access to a protected member _gpgme_key__refs_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:801:35: W0212: Access to a protected member _gpgme_key__refs_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:804:37: W0212: Access to a protected member _gpgme_key_revoked_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:805:37: W0212: Access to a protected member _gpgme_key_revoked_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:808:37: W0212: Access to a protected member _gpgme_key_expired_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:809:37: W0212: Access to a protected member _gpgme_key_expired_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:812:38: W0212: Access to a protected member _gpgme_key_disabled_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:813:38: W0212: Access to a protected member _gpgme_key_disabled_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:816:37: W0212: Access to a protected member _gpgme_key_invalid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:817:37: W0212: Access to a protected member _gpgme_key_invalid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:820:41: W0212: Access to a protected member _gpgme_key_can_encrypt_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:821:41: W0212: Access to a protected member _gpgme_key_can_encrypt_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:824:38: W0212: Access to a protected member _gpgme_key_can_sign_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:825:38: W0212: Access to a protected member _gpgme_key_can_sign_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:828:41: W0212: Access to a protected member _gpgme_key_can_certify_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:829:41: W0212: Access to a protected member _gpgme_key_can_certify_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:832:36: W0212: Access to a protected member _gpgme_key_secret_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:833:36: W0212: Access to a protected member _gpgme_key_secret_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:836:46: W0212: Access to a protected member _gpgme_key_can_authenticate_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:837:46: W0212: Access to a protected member _gpgme_key_can_authenticate_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:840:42: W0212: Access to a protected member _gpgme_key_is_qualified_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:841:42: W0212: Access to a protected member _gpgme_key_is_qualified_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:844:37: W0212: Access to a protected member _gpgme_key__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:845:37: W0212: Access to a protected member _gpgme_key__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:848:36: W0212: Access to a protected member _gpgme_key_origin_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:849:36: W0212: Access to a protected member _gpgme_key_origin_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:852:38: W0212: Access to a protected member _gpgme_key_protocol_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:853:38: W0212: Access to a protected member _gpgme_key_protocol_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:856:43: W0212: Access to a protected member _gpgme_key_issuer_serial_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:857:43: W0212: Access to a protected member _gpgme_key_issuer_serial_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:860:41: W0212: Access to a protected member _gpgme_key_issuer_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:861:41: W0212: Access to a protected member _gpgme_key_issuer_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:864:38: W0212: Access to a protected member _gpgme_key_chain_id_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:865:38: W0212: Access to a protected member _gpgme_key_chain_id_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:868:41: W0212: Access to a protected member _gpgme_key_owner_trust_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:869:41: W0212: Access to a protected member _gpgme_key_owner_trust_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:872:37: W0212: Access to a protected member _gpgme_key_subkeys_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:873:37: W0212: Access to a protected member _gpgme_key_subkeys_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:876:34: W0212: Access to a protected member _gpgme_key_uids_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:877:34: W0212: Access to a protected member _gpgme_key_uids_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:880:42: W0212: Access to a protected member _gpgme_key__last_subkey_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:881:42: W0212: Access to a protected member _gpgme_key__last_subkey_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:884:39: W0212: Access to a protected member _gpgme_key__last_uid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:885:39: W0212: Access to a protected member _gpgme_key__last_uid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:888:42: W0212: Access to a protected member _gpgme_key_keylist_mode_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:889:42: W0212: Access to a protected member _gpgme_key_keylist_mode_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:892:33: W0212: Access to a protected member _gpgme_key_fpr_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:893:33: W0212: Access to a protected member _gpgme_key_fpr_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:896:41: W0212: Access to a protected member _gpgme_key_last_update_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:897:41: W0212: Access to a protected member _gpgme_key_last_update_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:901:4: E0102: method already defined line 799 (function-redefined)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:915:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:914:12: E0203: Access to member 'this' before its definition line 916 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:792:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:919:26: W0212: Access to a protected member _gpgme_key_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:922:0: C0103: Class name "_gpgme_invalid_key" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:922:0: R0205: Class '_gpgme_invalid_key' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:930:33: W0212: Access to a protected member _gpgme_invalid_key_fpr_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:931:33: W0212: Access to a protected member _gpgme_invalid_key_fpr_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:934:36: W0212: Access to a protected member _gpgme_invalid_key_reason_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:935:36: W0212: Access to a protected member _gpgme_invalid_key_reason_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:944:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:943:12: E0203: Access to member 'this' before its definition line 945 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:922:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:948:34: W0212: Access to a protected member _gpgme_invalid_key_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1037:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1041:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1045:0: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1045:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1049:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1053:0: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1053:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1057:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1112:0: C0103: Class name "gpgme_io_event_done_data" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1112:0: R0205: Class 'gpgme_io_event_done_data' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1134:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1133:12: E0203: Access to member 'this' before its definition line 1135 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1112:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1141:0: C0103: Class name "gpgme_io_cbs" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1141:0: R0205: Class 'gpgme_io_cbs' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1175:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1174:12: E0203: Access to member 'this' before its definition line 1176 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1141:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1191:0: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1195:0: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1199:0: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1218:0: C0103: Class name "gpgme_data_cbs" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1218:0: R0205: Class 'gpgme_data_cbs' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1248:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1247:12: E0203: Access to member 'this' before its definition line 1249 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1218:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1256:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1260:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1268:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1276:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1284:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1288:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1288:0: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1292:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1300:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1304:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1308:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1312:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1316:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1320:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1328:0: C0103: Argument name "fp" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1332:0: C0103: Argument name "dh" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1355:0: C0103: Class name "_gpgme_op_encrypt_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1355:0: R0205: Class '_gpgme_op_encrypt_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1363:48: W0212: Access to a protected member _gpgme_op_encrypt_result_invalid_recipients_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1364:48: W0212: Access to a protected member _gpgme_op_encrypt_result_invalid_recipients_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1373:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1372:12: E0203: Access to member 'this' before its definition line 1374 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1355:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1377:40: W0212: Access to a protected member _gpgme_op_encrypt_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1402:0: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1406:0: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1418:0: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1422:0: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1425:0: C0103: Class name "_gpgme_recipient" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1425:0: R0205: Class '_gpgme_recipient' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1433:35: W0212: Access to a protected member _gpgme_recipient_keyid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1434:35: W0212: Access to a protected member _gpgme_recipient_keyid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1437:36: W0212: Access to a protected member _gpgme_recipient__keyid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1438:36: W0212: Access to a protected member _gpgme_recipient__keyid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1441:41: W0212: Access to a protected member _gpgme_recipient_pubkey_algo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1442:41: W0212: Access to a protected member _gpgme_recipient_pubkey_algo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1445:36: W0212: Access to a protected member _gpgme_recipient_status_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1446:36: W0212: Access to a protected member _gpgme_recipient_status_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1455:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1454:12: E0203: Access to member 'this' before its definition line 1456 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1425:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1459:32: W0212: Access to a protected member _gpgme_recipient_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1462:0: C0103: Class name "_gpgme_op_decrypt_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1462:0: R0205: Class '_gpgme_op_decrypt_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1470:51: W0212: Access to a protected member _gpgme_op_decrypt_result_unsupported_algorithm_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1471:51: W0212: Access to a protected member _gpgme_op_decrypt_result_unsupported_algorithm_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1474:45: W0212: Access to a protected member _gpgme_op_decrypt_result_wrong_key_usage_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1475:45: W0212: Access to a protected member _gpgme_op_decrypt_result_wrong_key_usage_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1478:38: W0212: Access to a protected member _gpgme_op_decrypt_result_is_de_vs_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1479:38: W0212: Access to a protected member _gpgme_op_decrypt_result_is_de_vs_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1482:37: W0212: Access to a protected member _gpgme_op_decrypt_result_is_mime_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1483:37: W0212: Access to a protected member _gpgme_op_decrypt_result_is_mime_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1486:49: W0212: Access to a protected member _gpgme_op_decrypt_result_legacy_cipher_nomdc_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1487:49: W0212: Access to a protected member _gpgme_op_decrypt_result_legacy_cipher_nomdc_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1490:37: W0212: Access to a protected member _gpgme_op_decrypt_result__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1491:37: W0212: Access to a protected member _gpgme_op_decrypt_result__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1494:40: W0212: Access to a protected member _gpgme_op_decrypt_result_recipients_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1495:40: W0212: Access to a protected member _gpgme_op_decrypt_result_recipients_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1498:39: W0212: Access to a protected member _gpgme_op_decrypt_result_file_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1499:39: W0212: Access to a protected member _gpgme_op_decrypt_result_file_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1502:41: W0212: Access to a protected member _gpgme_op_decrypt_result_session_key_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1503:41: W0212: Access to a protected member _gpgme_op_decrypt_result_session_key_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1506:41: W0212: Access to a protected member _gpgme_op_decrypt_result_symkey_algo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1507:41: W0212: Access to a protected member _gpgme_op_decrypt_result_symkey_algo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1516:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1515:12: E0203: Access to member 'this' before its definition line 1517 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1462:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1520:40: W0212: Access to a protected member _gpgme_op_decrypt_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1553:0: C0103: Class name "_gpgme_new_signature" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1553:0: R0205: Class '_gpgme_new_signature' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1561:34: W0212: Access to a protected member _gpgme_new_signature_type_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1562:34: W0212: Access to a protected member _gpgme_new_signature_type_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1565:41: W0212: Access to a protected member _gpgme_new_signature_pubkey_algo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1566:41: W0212: Access to a protected member _gpgme_new_signature_pubkey_algo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1569:39: W0212: Access to a protected member _gpgme_new_signature_hash_algo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1570:39: W0212: Access to a protected member _gpgme_new_signature_hash_algo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1573:45: W0212: Access to a protected member _gpgme_new_signature__obsolete_class_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1574:45: W0212: Access to a protected member _gpgme_new_signature__obsolete_class_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1577:39: W0212: Access to a protected member _gpgme_new_signature_timestamp_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1578:39: W0212: Access to a protected member _gpgme_new_signature_timestamp_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1581:33: W0212: Access to a protected member _gpgme_new_signature_fpr_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1582:33: W0212: Access to a protected member _gpgme_new_signature_fpr_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1585:47: W0212: Access to a protected member _gpgme_new_signature__obsolete_class_2_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1586:47: W0212: Access to a protected member _gpgme_new_signature__obsolete_class_2_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1589:39: W0212: Access to a protected member _gpgme_new_signature_sig_class_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1590:39: W0212: Access to a protected member _gpgme_new_signature_sig_class_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1599:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1598:12: E0203: Access to member 'this' before its definition line 1600 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1553:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1603:36: W0212: Access to a protected member _gpgme_new_signature_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1606:0: C0103: Class name "_gpgme_op_sign_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1606:0: R0205: Class '_gpgme_op_sign_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1614:45: W0212: Access to a protected member _gpgme_op_sign_result_invalid_signers_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1615:45: W0212: Access to a protected member _gpgme_op_sign_result_invalid_signers_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1618:40: W0212: Access to a protected member _gpgme_op_sign_result_signatures_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1619:40: W0212: Access to a protected member _gpgme_op_sign_result_signatures_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1628:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1627:12: E0203: Access to member 'this' before its definition line 1629 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1606:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1632:37: W0212: Access to a protected member _gpgme_op_sign_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1659:0: C0103: Class name "_gpgme_signature" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1659:0: R0205: Class '_gpgme_signature' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1667:37: W0212: Access to a protected member _gpgme_signature_summary_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1668:37: W0212: Access to a protected member _gpgme_signature_summary_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1671:33: W0212: Access to a protected member _gpgme_signature_fpr_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1672:33: W0212: Access to a protected member _gpgme_signature_fpr_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1675:36: W0212: Access to a protected member _gpgme_signature_status_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1676:36: W0212: Access to a protected member _gpgme_signature_status_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1679:39: W0212: Access to a protected member _gpgme_signature_notations_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1680:39: W0212: Access to a protected member _gpgme_signature_notations_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1683:39: W0212: Access to a protected member _gpgme_signature_timestamp_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1684:39: W0212: Access to a protected member _gpgme_signature_timestamp_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1687:43: W0212: Access to a protected member _gpgme_signature_exp_timestamp_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1688:43: W0212: Access to a protected member _gpgme_signature_exp_timestamp_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1691:45: W0212: Access to a protected member _gpgme_signature_wrong_key_usage_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1692:45: W0212: Access to a protected member _gpgme_signature_wrong_key_usage_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1695:39: W0212: Access to a protected member _gpgme_signature_pka_trust_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1696:39: W0212: Access to a protected member _gpgme_signature_pka_trust_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1699:41: W0212: Access to a protected member _gpgme_signature_chain_model_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1700:41: W0212: Access to a protected member _gpgme_signature_chain_model_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1703:38: W0212: Access to a protected member _gpgme_signature_is_de_vs_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1704:38: W0212: Access to a protected member _gpgme_signature_is_de_vs_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1707:37: W0212: Access to a protected member _gpgme_signature__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1708:37: W0212: Access to a protected member _gpgme_signature__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1711:38: W0212: Access to a protected member _gpgme_signature_validity_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1712:38: W0212: Access to a protected member _gpgme_signature_validity_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1715:45: W0212: Access to a protected member _gpgme_signature_validity_reason_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1716:45: W0212: Access to a protected member _gpgme_signature_validity_reason_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1719:41: W0212: Access to a protected member _gpgme_signature_pubkey_algo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1720:41: W0212: Access to a protected member _gpgme_signature_pubkey_algo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1723:39: W0212: Access to a protected member _gpgme_signature_hash_algo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1724:39: W0212: Access to a protected member _gpgme_signature_hash_algo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1727:41: W0212: Access to a protected member _gpgme_signature_pka_address_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1728:41: W0212: Access to a protected member _gpgme_signature_pka_address_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1731:33: W0212: Access to a protected member _gpgme_signature_key_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1732:33: W0212: Access to a protected member _gpgme_signature_key_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1741:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1740:12: E0203: Access to member 'this' before its definition line 1742 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1659:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1745:32: W0212: Access to a protected member _gpgme_signature_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1748:0: C0103: Class name "_gpgme_op_verify_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1748:0: R0205: Class '_gpgme_op_verify_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1756:40: W0212: Access to a protected member _gpgme_op_verify_result_signatures_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1757:40: W0212: Access to a protected member _gpgme_op_verify_result_signatures_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1760:39: W0212: Access to a protected member _gpgme_op_verify_result_file_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1761:39: W0212: Access to a protected member _gpgme_op_verify_result_file_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1764:37: W0212: Access to a protected member _gpgme_op_verify_result_is_mime_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1765:37: W0212: Access to a protected member _gpgme_op_verify_result_is_mime_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1768:37: W0212: Access to a protected member _gpgme_op_verify_result__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1769:37: W0212: Access to a protected member _gpgme_op_verify_result__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1778:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1777:12: E0203: Access to member 'this' before its definition line 1779 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1748:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1782:39: W0212: Access to a protected member _gpgme_op_verify_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1802:0: C0103: Class name "_gpgme_import_status" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1802:0: R0205: Class '_gpgme_import_status' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1810:33: W0212: Access to a protected member _gpgme_import_status_fpr_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1811:33: W0212: Access to a protected member _gpgme_import_status_fpr_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1814:36: W0212: Access to a protected member _gpgme_import_status_result_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1815:36: W0212: Access to a protected member _gpgme_import_status_result_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1818:36: W0212: Access to a protected member _gpgme_import_status_status_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1819:36: W0212: Access to a protected member _gpgme_import_status_status_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1828:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1827:12: E0203: Access to member 'this' before its definition line 1829 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1802:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1832:36: W0212: Access to a protected member _gpgme_import_status_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1835:0: C0103: Class name "_gpgme_op_import_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1835:0: R0205: Class '_gpgme_op_import_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1843:40: W0212: Access to a protected member _gpgme_op_import_result_considered_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1844:40: W0212: Access to a protected member _gpgme_op_import_result_considered_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1847:40: W0212: Access to a protected member _gpgme_op_import_result_no_user_id_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1848:40: W0212: Access to a protected member _gpgme_op_import_result_no_user_id_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1851:38: W0212: Access to a protected member _gpgme_op_import_result_imported_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1852:38: W0212: Access to a protected member _gpgme_op_import_result_imported_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1855:42: W0212: Access to a protected member _gpgme_op_import_result_imported_rsa_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1856:42: W0212: Access to a protected member _gpgme_op_import_result_imported_rsa_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1859:39: W0212: Access to a protected member _gpgme_op_import_result_unchanged_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1860:39: W0212: Access to a protected member _gpgme_op_import_result_unchanged_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1863:42: W0212: Access to a protected member _gpgme_op_import_result_new_user_ids_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1864:42: W0212: Access to a protected member _gpgme_op_import_result_new_user_ids_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1867:42: W0212: Access to a protected member _gpgme_op_import_result_new_sub_keys_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1868:42: W0212: Access to a protected member _gpgme_op_import_result_new_sub_keys_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1871:44: W0212: Access to a protected member _gpgme_op_import_result_new_signatures_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1872:44: W0212: Access to a protected member _gpgme_op_import_result_new_signatures_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1875:45: W0212: Access to a protected member _gpgme_op_import_result_new_revocations_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1876:45: W0212: Access to a protected member _gpgme_op_import_result_new_revocations_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1879:41: W0212: Access to a protected member _gpgme_op_import_result_secret_read_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1880:41: W0212: Access to a protected member _gpgme_op_import_result_secret_read_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1883:45: W0212: Access to a protected member _gpgme_op_import_result_secret_imported_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1884:45: W0212: Access to a protected member _gpgme_op_import_result_secret_imported_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1887:46: W0212: Access to a protected member _gpgme_op_import_result_secret_unchanged_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1888:46: W0212: Access to a protected member _gpgme_op_import_result_secret_unchanged_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1891:46: W0212: Access to a protected member _gpgme_op_import_result_skipped_new_keys_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1892:46: W0212: Access to a protected member _gpgme_op_import_result_skipped_new_keys_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1895:42: W0212: Access to a protected member _gpgme_op_import_result_not_imported_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1896:42: W0212: Access to a protected member _gpgme_op_import_result_not_imported_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1899:37: W0212: Access to a protected member _gpgme_op_import_result_imports_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1900:37: W0212: Access to a protected member _gpgme_op_import_result_imports_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1903:45: W0212: Access to a protected member _gpgme_op_import_result_skipped_v3_keys_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1904:45: W0212: Access to a protected member _gpgme_op_import_result_skipped_v3_keys_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1913:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1912:12: E0203: Access to member 'this' before its definition line 1914 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1835:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1917:39: W0212: Access to a protected member _gpgme_op_import_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1975:0: C0103: Class name "_gpgme_op_genkey_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1975:0: R0205: Class '_gpgme_op_genkey_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1983:37: W0212: Access to a protected member _gpgme_op_genkey_result_primary_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1984:37: W0212: Access to a protected member _gpgme_op_genkey_result_primary_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1987:33: W0212: Access to a protected member _gpgme_op_genkey_result_sub_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1988:33: W0212: Access to a protected member _gpgme_op_genkey_result_sub_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1991:33: W0212: Access to a protected member _gpgme_op_genkey_result_uid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1992:33: W0212: Access to a protected member _gpgme_op_genkey_result_uid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1995:37: W0212: Access to a protected member _gpgme_op_genkey_result__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1996:37: W0212: Access to a protected member _gpgme_op_genkey_result__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1999:33: W0212: Access to a protected member _gpgme_op_genkey_result_fpr_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2000:33: W0212: Access to a protected member _gpgme_op_genkey_result_fpr_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2003:36: W0212: Access to a protected member _gpgme_op_genkey_result_pubkey_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2004:36: W0212: Access to a protected member _gpgme_op_genkey_result_pubkey_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2007:36: W0212: Access to a protected member _gpgme_op_genkey_result_seckey_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2008:36: W0212: Access to a protected member _gpgme_op_genkey_result_seckey_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2017:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2016:12: E0203: Access to member 'this' before its definition line 2018 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:1975:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2021:39: W0212: Access to a protected member _gpgme_op_genkey_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2033:0: R0913: Too many arguments (7/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2037:0: R0913: Too many arguments (7/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2041:0: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2045:0: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2122:0: C0103: Class name "_gpgme_op_keylist_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2122:0: R0205: Class '_gpgme_op_keylist_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2130:39: W0212: Access to a protected member _gpgme_op_keylist_result_truncated_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2131:39: W0212: Access to a protected member _gpgme_op_keylist_result_truncated_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2134:37: W0212: Access to a protected member _gpgme_op_keylist_result__unused_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2135:37: W0212: Access to a protected member _gpgme_op_keylist_result__unused_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2144:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2143:12: E0203: Access to member 'this' before its definition line 2145 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2122:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2148:40: W0212: Access to a protected member _gpgme_op_keylist_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2179:0: C0103: Class name "_gpgme_trust_item" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2179:0: R0205: Class '_gpgme_trust_item' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2187:35: W0212: Access to a protected member _gpgme_trust_item__refs_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2188:35: W0212: Access to a protected member _gpgme_trust_item__refs_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2191:35: W0212: Access to a protected member _gpgme_trust_item_keyid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2192:35: W0212: Access to a protected member _gpgme_trust_item_keyid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2195:36: W0212: Access to a protected member _gpgme_trust_item__keyid_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2196:36: W0212: Access to a protected member _gpgme_trust_item__keyid_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2199:34: W0212: Access to a protected member _gpgme_trust_item_type_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2200:34: W0212: Access to a protected member _gpgme_trust_item_type_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2203:35: W0212: Access to a protected member _gpgme_trust_item_level_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2204:35: W0212: Access to a protected member _gpgme_trust_item_level_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2207:41: W0212: Access to a protected member _gpgme_trust_item_owner_trust_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2208:41: W0212: Access to a protected member _gpgme_trust_item_owner_trust_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2211:42: W0212: Access to a protected member _gpgme_trust_item__owner_trust_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2212:42: W0212: Access to a protected member _gpgme_trust_item__owner_trust_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2215:38: W0212: Access to a protected member _gpgme_trust_item_validity_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2216:38: W0212: Access to a protected member _gpgme_trust_item_validity_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2219:39: W0212: Access to a protected member _gpgme_trust_item__validity_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2220:39: W0212: Access to a protected member _gpgme_trust_item__validity_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2223:34: W0212: Access to a protected member _gpgme_trust_item_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2224:34: W0212: Access to a protected member _gpgme_trust_item_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2233:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2232:12: E0203: Access to member 'this' before its definition line 2234 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2179:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2237:33: W0212: Access to a protected member _gpgme_trust_item_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2272:0: R0913: Too many arguments (7/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2276:0: R0913: Too many arguments (7/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2284:0: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2287:0: C0103: Class name "_gpgme_op_vfs_mount_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2287:0: R0205: Class '_gpgme_op_vfs_mount_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2295:39: W0212: Access to a protected member _gpgme_op_vfs_mount_result_mount_dir_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2296:39: W0212: Access to a protected member _gpgme_op_vfs_mount_result_mount_dir_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2305:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2304:12: E0203: Access to member 'this' before its definition line 2306 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2287:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2309:42: W0212: Access to a protected member _gpgme_op_vfs_mount_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2339:0: C0103: Class name "gpgme_conf_arg" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2339:0: R0205: Class 'gpgme_conf_arg' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2360:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2359:12: E0203: Access to member 'this' before its definition line 2361 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2339:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2367:0: C0103: Class name "gpgme_conf_arg_value" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2367:0: R0205: Class 'gpgme_conf_arg_value' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2397:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2396:12: E0203: Access to member 'this' before its definition line 2398 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2367:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2412:0: C0103: Class name "gpgme_conf_opt" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2412:0: R0205: Class 'gpgme_conf_opt' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2486:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2485:12: E0203: Access to member 'this' before its definition line 2487 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2412:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2493:0: C0103: Class name "gpgme_conf_comp" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2493:0: R0205: Class 'gpgme_conf_comp' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2527:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2526:12: E0203: Access to member 'this' before its definition line 2528 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2493:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2535:52: W0622: Redefining built-in 'type' (redefined-builtin)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2539:50: W0622: Redefining built-in 'type' (redefined-builtin)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2562:0: C0103: Class name "_gpgme_op_query_swdb_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2562:0: R0205: Class '_gpgme_op_query_swdb_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2570:34: W0212: Access to a protected member _gpgme_op_query_swdb_result_name_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2571:34: W0212: Access to a protected member _gpgme_op_query_swdb_result_name_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2574:38: W0212: Access to a protected member _gpgme_op_query_swdb_result_iversion_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2575:38: W0212: Access to a protected member _gpgme_op_query_swdb_result_iversion_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2578:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_created_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2579:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_created_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2582:39: W0212: Access to a protected member _gpgme_op_query_swdb_result_retrieved_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2583:39: W0212: Access to a protected member _gpgme_op_query_swdb_result_retrieved_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2586:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_warning_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2587:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_warning_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2590:36: W0212: Access to a protected member _gpgme_op_query_swdb_result_update_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2591:36: W0212: Access to a protected member _gpgme_op_query_swdb_result_update_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2594:36: W0212: Access to a protected member _gpgme_op_query_swdb_result_urgent_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2595:36: W0212: Access to a protected member _gpgme_op_query_swdb_result_urgent_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2598:36: W0212: Access to a protected member _gpgme_op_query_swdb_result_noinfo_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2599:36: W0212: Access to a protected member _gpgme_op_query_swdb_result_noinfo_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2602:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_unknown_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2603:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_unknown_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2606:36: W0212: Access to a protected member _gpgme_op_query_swdb_result_tooold_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2607:36: W0212: Access to a protected member _gpgme_op_query_swdb_result_tooold_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2610:35: W0212: Access to a protected member _gpgme_op_query_swdb_result_error_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2611:35: W0212: Access to a protected member _gpgme_op_query_swdb_result_error_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2614:39: W0212: Access to a protected member _gpgme_op_query_swdb_result__reserved_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2615:39: W0212: Access to a protected member _gpgme_op_query_swdb_result__reserved_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2618:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_version_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2619:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_version_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2622:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_reldate_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2623:37: W0212: Access to a protected member _gpgme_op_query_swdb_result_reldate_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2632:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2631:12: E0203: Access to member 'this' before its definition line 2633 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2562:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2636:43: W0212: Access to a protected member _gpgme_op_query_swdb_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2862:0: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2866:0: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2894:0: C0103: Argument name "nr" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2909:0: C0103: Class name "_gpgme_op_assuan_result" doesn't conform to PascalCase naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2909:0: R0205: Class '_gpgme_op_assuan_result' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2917:33: W0212: Access to a protected member _gpgme_op_assuan_result_err_set of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2918:33: W0212: Access to a protected member _gpgme_op_assuan_result_err_get of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2927:15: W0703: Catching too general exception Exception (broad-except)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2926:12: E0203: Access to member 'this' before its definition line 2928 (access-member-before-definition)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2909:0: R0903: Too few public methods (0/2) (too-few-public-methods)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2931:39: W0212: Access to a protected member _gpgme_op_assuan_result_swigregister of a client class (protected-access)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:2939:0: R0913: Too many arguments (6/5) (too-many-arguments)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:3674:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:3678:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<pre>/log/firmware/firmware/usr/lib/python3.8/site-packages/gpg/gpgme.py:3682:0: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)</pre>
<br />
<pre>-----------------------------------</pre>
<pre>Your code has been rated at 7.35/10</pre>
<br />
  <!-- content end -->
</div>

<a href="https://github.com/e-m-b-a/emba" title="github.com/e-m-b-a/emba" target="_blank">
  <div id="buttonInfo" class="rectButtonVisible">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" transform="translate(2 2)"><g stroke="white" stroke-linecap="round" stroke-linejoin="round"><circle cx="8.5" cy="8.5" r="8"/><path d="M8.5 12.5v-4h-1"/><path d="M7.5 12.5h2"/></g><circle cx="8.5" cy="5.5" fill="white" r="1"/></g></svg>
  </div>
</a>
<div id="buttonBack" class="nonClickable rectButtonVisible"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><path d="M9.5 14.5l4-4l-4-4" fill="none" stroke="#444" stroke-linecap="round" stroke-linejoin="round"/></svg></div>
<div id="buttonForward" class="nonClickable rectButtonVisible"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><path d="M11.5 14.5l-4-4l4-4" fill="none" stroke="#444" stroke-linecap="round" stroke-linejoin="round"/></svg></div> 
<div id="buttonDown" class="rectButton" onclick="scrollDown()"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="#fff" stroke-linecap="round" stroke-linejoin="round"><path d="M14.5 6.5l-4 4l-4-4"/><path d="M14.5 10.5l-4 4l-4-4"/></g></svg></div>
<div id="buttonUp" class="rectButton" onclick="scrollUp()"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="#fff" stroke-linecap="round" stroke-linejoin="round"><path d="M6.5 14.5l4-4l4 4"/><path d="M6.5 10.5l4-4l4 4"/></g></svg></div> 

<script>
window.onload = function () {
  var buttons = document.getElementsByClassName("rectButton");
  for (let i=0; i<buttons.length; i++) {
    buttons[i].style.visibility = "visible";
  }
  var buttonDown = document.getElementById("buttonDown");
  buttonDown.classList.add('rectButtonVisible');
  buttonDown.classList.remove('rectButton');

  var buttonUp = document.getElementById("buttonUp");
  buttonUp.classList.add('rectButtonVisible');
  buttonUp.classList.remove('rectButton');
    
  var buttonSizer = document.getElementById("buttonSizer");
  buttonSizer.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="white" stroke-linecap="round" stroke-linejoin="round"><path d="M9.5 16.5v-4.978l-5-.022"/><path d="M18.5 2.5l-7 7"/><path d="M16.5 9.5l-5 .023V4.5"/><path d="M9.5 11.5l-7 7"/></g></svg>';
  if (document.getElementById("buttonTime") !== null) {
    var buttonTime = document.getElementById("buttonTime");
    buttonTime.style.bottom = "50px";
  }
  document.getElementById("expand").value = "+ Show more results";
  document.getElementById("expand").className += " expand";
}

function openNav() {
  document.getElementById("sidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
  document.getElementById("nav").style.visibility = "visible";
}

function closeNav() {
  document.getElementById("sidenav").style.width = "50px";
  document.getElementById("sidenav").scrollTop = 0;
  document.getElementById("main").style.marginLeft = "50px";
  document.getElementById("nav").style.visibility = "hidden";
}

function scrollDown() {
  window.scrollTo(0,document.body.scrollHeight);
}

function scrollUp() {
  window.scrollTo(0,0);
}

function buttonNav() {
  var button = document.getElementById("buttonSizer");
  if ( button.classList.contains('buttonOpen') ) {
    button.classList.remove('buttonOpen');
    button.classList.add('buttonClose');
    button.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="white" stroke-linecap="round" stroke-linejoin="round"><path d="M9.5 16.5v-4.978l-5-.022"/><path d="M18.5 2.5l-7 7"/><path d="M16.5 9.5l-5 .023V4.5"/><path d="M9.5 11.5l-7 7"/></g></svg>';
    openNav();
  } else if( button.classList.contains('buttonClose') ) {
    button.classList.remove('buttonClose');
    button.classList.add('buttonOpen');
    button.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="40" height="40" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="white" stroke-linecap="round" stroke-linejoin="round"><path d="M18.5 7.5v-5h-5"/><path d="M18.5 2.5l-6 5.929"/><path d="M7.5 18.5l-5 .023V13.5"/><path d="M8.5 12.5l-6 6"/></g></svg>';
    closeNav();
  };
}

document.onkeydown = function(e) {
    switch (e.keyCode) {
      case 37:
        document.getElementById("buttonForward").parentNode.click(); 
        break;
      case 39:
        document.getElementById("buttonBack").parentNode.click();       
        break;
    }
};
</script>

</body>
</html>
