************* Module lib2to3.pgen2.conv
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:36:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:62:12: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:71:12: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:84:4: R0914: Too many local variables (33/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:113:12: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:132:16: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:135:16: C0103: Variable name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:135:19: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:139:20: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:147:12: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:149:12: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:149:15: C0103: Variable name "t" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:154:16: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:156:19: C0103: Variable name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:156:22: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:168:8: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:173:12: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:177:20: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:177:23: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:177:26: C0103: Variable name "z" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:184:12: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:187:24: W0123: Use of eval (eval-used)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:188:12: W0621: Redefining name 'i' from outer scope (line 171) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:188:19: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:201:8: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:206:12: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:208:12: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:208:15: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:209:12: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:211:16: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:213:16: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:213:20: W0123: Use of eval (eval-used)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:223:8: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:230:8: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:235:8: C0103: Variable name "mo" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:84:4: R0912: Too many branches (14/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:84:4: R0915: Too many statements (115/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:253:21: W0622: Redefining built-in 'type' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:66:8: W0201: Attribute 'symbol2number' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:67:8: W0201: Attribute 'number2symbol' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:164:8: W0201: Attribute 'states' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:196:8: W0201: Attribute 'dfas' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:217:8: W0201: Attribute 'labels' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:239:8: W0201: Attribute 'start' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:251:8: W0201: Attribute 'keywords' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/lib2to3/pgen2/conv.py:252:8: W0201: Attribute 'tokens' defined outside __init__ (attribute-defined-outside-init)

-----------------------------------
Your code has been rated at 7.09/10

