************* Module asyncio.sslproto
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:36:0: R0205: Class '_SSLPipe' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:36:0: R0902: Too many instance attributes (10/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:144:15: R1714: Consider merging these comparisons with "in" to "appdata in ([], [b''])" (consider-using-in)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:155:15: R1714: Consider merging these comparisons with "in" to "appdata in ([], [b''])" (consider-using-in)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:154:8: W0612: Unused variable 'ssldata' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:228:8: W0125: Using a conditional statement with a constant value (using-constant-test)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:157:4: R0912: Too many branches (17/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:277:12: W0125: Using a conditional statement with a constant value (using-constant-test)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:284:28: W0212: Access to a protected member _FlowControlMixin of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:287:27: W0212: Access to a protected member _SendfileMode of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:297:15: W0212: Access to a protected member _get_extra_info of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:300:8: W0212: Access to a protected member _set_app_protocol of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:303:15: W0212: Access to a protected member _app_protocol of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:317:8: W0212: Access to a protected member _start_shutdown of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:325:8: C0103: Variable name "tr" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:325:13: W0212: Access to a protected member _transport of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:336:8: W0212: Access to a protected member _transport of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:344:8: W0212: Access to a protected member _transport of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:365:8: W0212: Access to a protected member _transport of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:369:15: W0212: Access to a protected member _transport of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:374:15: W0212: Access to a protected member _protocol_paused of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:374:15: W0212: Access to a protected member _transport of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:387:8: W0212: Access to a protected member _write_appdata of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:389:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:400:8: W0212: Access to a protected member _abort of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:404:0: R0902: Too many instance attributes (20/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:411:4: R0913: Too many arguments (9/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:498:16: W0212: Access to a protected member _closed of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:532:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:532:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:549:23: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:543:24: W0212: Access to a protected member _feed_data_to_buffered_proto of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:580:8: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:637:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:646:12: C0103: Variable name "dt" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:702:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:692:23: W0212: Access to a protected member _paused of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:672:16: W0612: Unused variable 'i' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:721:12: W0212: Access to a protected member _force_close of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:504:8: W0201: Attribute '_app_protocol' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:604:12: W0201: Attribute '_handshake_start_time' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:606:12: W0201: Attribute '_handshake_start_time' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:611:8: W0201: Attribute '_handshake_timeout_handle' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/asyncio/sslproto.py:8:0: W0611: Unused import base_events (unused-import)

-----------------------------------
Your code has been rated at 8.84/10

