************* Module pip._internal.models.direct_url
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:15:0: C0103: Class name "T" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:25:0: C0103: Argument name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:41:0: C0103: Argument name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:72:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:87:4: C0103: Argument name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:69:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:113:8: W0622: Redefining built-in 'hash' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:118:4: C0103: Argument name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:108:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:137:4: C0103: Argument name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:127:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:191:4: C0103: Argument name "d" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:197:20: W0212: Access to a protected member _from_dict of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:198:20: W0212: Access to a protected member _from_dict of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:199:20: W0212: Access to a protected member _from_dict of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:209:30: W0212: Access to a protected member _to_dict of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_internal/models/direct_url.py:213:4: C0103: Argument name "s" doesn't conform to snake_case naming style (invalid-name)

-----------------------------------
Your code has been rated at 8.30/10

