************* Module pip._vendor.urllib3.connectionpool
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:1:0: C0302: Too many lines in module (1078/1000) (too-many-lines)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:11:0: W0622: Redefining built-in 'BrokenPipeError' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:21:0: W0622: Redefining built-in 'TimeoutError' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:52:9: E1101: Instance of '_MovedItems' has no 'xrange' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:60:0: R0205: Class 'ConnectionPool' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:97:8: W0107: Unnecessary pass statement (unnecessary-pass)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:104:0: R0902: Too many instance attributes (11/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:168:4: R0913: Too many arguments (12/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:260:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:264:16: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:268:12: W0107: Unnecessary pass statement (unnecessary-pass)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:314:8: W0107: Unnecessary pass statement (unnecessary-pass)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:325:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:357:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:383:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:402:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:441:23: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:441:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:446:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:357:4: R0912: Too many branches (14/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:518:4: W0221: Parameters differ from overridden 'urlopen' method (arguments-differ)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:518:4: R0913: Too many arguments (13/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:518:4: R0914: Too many local variables (29/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:736:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:749:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:751:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:753:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:518:4: R0912: Too many branches (25/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:518:4: R0915: Too many statements (85/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:865:0: R0902: Too many instance attributes (10/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:882:4: R0913: Too many arguments (20/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:882:4: R0914: Too many local variables (19/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:1006:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
/log/firmware/firmware/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py:1057:4: R1705: Unnecessary "else" after "return" (no-else-return)

-----------------------------------
Your code has been rated at 8.86/10

