************* Module asyncio.coroutines
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:64:20: W0622: Redefining built-in 'type' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:64:38: W0621: Redefining name 'traceback' from outer scope (line 8) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:95:12: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:97:16: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:145:12: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:146:15: W0212: Access to a protected member _source_traceback of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:147:20: W0212: Access to a protected member _source_traceback of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:156:4: W0212: Access to a protected member _is_coroutine of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:182:4: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:204:19: W0212: Access to a protected member _format_callback of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:234:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:253:17: W0212: Access to a protected member _get_function_source of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/coroutines.py:193:0: R0912: Too many branches (13/12) (too-many-branches)

-----------------------------------
Your code has been rated at 9.15/10

