************* Module setuptools.command.py36compat
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:6:0: W0622: Redefining built-in 'filter' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:6:0: E0611: No name 'six' in module 'setuptools.extern' (no-name-in-module)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:9:0: C0103: Class name "sdist_add_defaults" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:58:21: E1101: Instance of 'sdist_add_defaults' has no 'READMES' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:58:35: E1101: Instance of 'sdist_add_defaults' has no 'distribution' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:59:12: C0103: Variable name "fn" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:63:16: W0621: Redefining name 'fn' from outer scope (line 59) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:63:20: C0103: Variable name "fn" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:66:24: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:70:20: E1101: Instance of 'sdist_add_defaults' has no 'warn' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:74:20: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:76:20: E1101: Instance of 'sdist_add_defaults' has no 'warn' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:82:12: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:88:19: E1101: Instance of 'sdist_add_defaults' has no 'get_finalized_command' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:91:11: E1101: Instance of 'sdist_add_defaults' has no 'distribution' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:92:12: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:98:16: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:96:12: W0612: Unused variable 'pkg' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:96:26: W0612: Unused variable 'build_dir' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:102:11: E1101: Instance of 'sdist_add_defaults' has no 'distribution' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:103:24: E1101: Instance of 'sdist_add_defaults' has no 'distribution' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:108:24: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:112:24: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:113:24: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:115:28: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:111:20: W0612: Unused variable 'dirname' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:118:11: E1101: Instance of 'sdist_add_defaults' has no 'distribution' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:119:24: E1101: Instance of 'sdist_add_defaults' has no 'get_finalized_command' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:120:12: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:123:11: E1101: Instance of 'sdist_add_defaults' has no 'distribution' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:124:25: E1101: Instance of 'sdist_add_defaults' has no 'get_finalized_command' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:125:12: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:128:11: E1101: Instance of 'sdist_add_defaults' has no 'distribution' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:129:28: E1101: Instance of 'sdist_add_defaults' has no 'get_finalized_command' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:130:12: E1101: Instance of 'sdist_add_defaults' has no 'filelist' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:9:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:135:4: E0102: class already defined line 9 (function-redefined)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:135:4: C0103: Class name "sdist_add_defaults" doesn't conform to PascalCase naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/setuptools/command/py36compat.py:135:4: R0903: Too few public methods (0/2) (too-few-public-methods)

------------------------------------
Your code has been rated at -9.07/10

