************* Module idlelib.debugger_r
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:26:0: C0103: Constant name "debugging" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:28:0: C0103: Constant name "idb_adap_oid" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:29:0: C0103: Constant name "gui_adap_oid" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:47:4: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:59:29: W0621: Redefining name 'gui_adap_oid' from outer scope (line 29) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:57:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:97:12: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:99:12: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:105:8: C0415: Import outside toplevel (__main__) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:122:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:128:8: W0622: Redefining built-in 'dict' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:126:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:135:8: W0622: Redefining built-in 'dict' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:133:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:140:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:149:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:153:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:167:8: W0622: Redefining built-in 'dict' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:166:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:171:8: W0622: Redefining built-in 'dict' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:170:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:179:31: W0621: Redefining name 'gui_adap_oid' from outer scope (line 29) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:238:8: C0103: Variable name "dp" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:201:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:250:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:243:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:283:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:308:23: W0622: Redefining built-in 'locals' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:308:23: W0613: Unused argument 'locals' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:315:42: W0212: Access to a protected member _fid of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:326:30: W0212: Access to a protected member _fid of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:329:32: W0212: Access to a protected member _fid of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:360:4: C0103: Constant name "idb_adap_oid" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/idlelib/debugger_r.py:360:4: W0603: Using the global statement (global-statement)

-----------------------------------
Your code has been rated at 8.44/10

