************* Module concurrent.futures.process
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:78:0: C0103: Constant name "_global_shutdown" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:98:4: C0103: Constant name "_global_shutdown" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:98:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:103:8: C0103: Variable name "t" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:123:8: C0103: Attribute name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:122:4: W0231: __init__ method from base class 'Exception' is not called (super-init-not-called)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:132:8: C0103: Attribute name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:127:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:136:0: C0103: Argument name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:143:8: C0103: Attribute name "fn" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:140:0: R0205: Class '_WorkItem' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:140:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:147:0: R0205: Class '_ResultItem' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:147:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:156:8: C0103: Attribute name "fn" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:153:0: R0205: Class '_CallItem' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:153:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:169:12: C0103: Variable name "tb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:182:4: C0103: Variable name "it" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:189:0: C0103: Argument name "fn" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:206:11: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:206:4: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:227:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:240:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:239:12: C0103: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:240:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:290:0: R0913: Too many arguments (7/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:290:0: R0914: Too many local variables (23/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:322:19: W0212: Access to a protected member _shutdown_thread of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:344:12: C0103: Variable name "p" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:332:16: W0612: Unused variable 'i' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:347:20: W0212: Access to a protected member _reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:348:20: W0212: Access to a protected member _reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:370:19: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:370:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:381:16: W0212: Access to a protected member _broken of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:384:16: W0212: Access to a protected member _shutdown_thread of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:400:16: C0103: Variable name "p" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:408:12: C0103: Variable name "p" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:437:20: W0212: Access to a protected member _shutdown_thread of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:393:16: W0612: Unused variable 'work_id' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:290:0: R0912: Too many branches (19/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:290:0: R0915: Too many statements (70/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:450:0: C0103: Constant name "_system_limits_checked" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:451:0: C0103: Constant name "_system_limited" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:455:4: C0103: Constant name "_system_limits_checked" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:455:4: C0103: Constant name "_system_limited" doesn't conform to UPPER_CASE naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:455:4: W0603: Using the global statement (global-statement)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:497:0: R0902: Too many instance attributes (15/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:519:12: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:602:12: C0103: Variable name "p" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:611:4: E0211: Method has no argument (no-method-argument)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:613:18: C0103: Variable name "fn" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:618:12: C0103: Variable name "fn" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:620:12: C0415: Import outside toplevel (warnings) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:627:13: W0212: Access to a protected member _shutdown_lock of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:628:15: W0212: Access to a protected member _broken of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:629:40: W0212: Access to a protected member _broken of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:630:15: W0212: Access to a protected member _shutdown_thread of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:636:12: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:637:12: C0103: Variable name "w" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:639:12: W0212: Access to a protected member _pending_work_items of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:639:37: W0212: Access to a protected member _queue_count of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:640:12: W0212: Access to a protected member _work_ids of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:640:31: W0212: Access to a protected member _queue_count of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:643:12: W0212: Access to a protected member _queue_management_thread_wakeup of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:645:12: W0212: Access to a protected member _start_queue_management_thread of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/concurrent/futures/process.py:54:0: W0611: Unused import multiprocessing.connection (unused-import)

-----------------------------------
Your code has been rated at 7.86/10

